sudo: false
language: node_js
node_js:
  - lts/*
cache:
  yarn: true
  directories:
    - node_modules
script:
  - npm test
  - npm run doc
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master
notifications:
  email:
    on_success: never
